# Generated by Django 3.2.9 on 2021-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank='', default=',upload_to=photos/', upload_to=''),
        ),
    ]
